// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UygulamaHavuzu_1._0.Models;

namespace UygulamaHavuzu_1._0.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230828104649_AddTamamlandiMiForYapmaListesi")]
    partial class AddTamamlandiMiForYapmaListesi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UygulamaHavuzu_1._0.Models.YapmaListesi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Do")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("TamamlandiMi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Todo_tablo");
                });
#pragma warning restore 612, 618
        }
    }
}
